server:
  port: 8888

spring:
  application:
    name: rocketmq
  cloud:
    stream:
      bindings:
        # 定义name为input的binding
        input:
          #          content-type: application/json
          destination: test-topic
          group: test-group
        # 定义name为output的binding
        output:
          #          content-type: application/json
          destination: test-topic
      rocketmq:
        binder:
          name-server: localhost:9876

