server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: false # 获取服务中心的其它服务

      routes:
        - id: useless
          uri: lb://service-provider
          predicates:
            - Path=/echo/{segment} # 访问 path 会自动在前面拼上 {serviceName}

#service-provider:
#  ribbon:
#    listOfServers: localhost:8070, localhost:8071
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule