spring:
  shardingsphere:
    # 数据源（略）
    datasource:
      ds_master_0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds_master_0?serverTimezone=UTC&useSSL=false
        max-active: 16
        password: ''
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      ds_master_0_slave_0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds_master_0_slave_0?serverTimezone=UTC&useSSL=false
        max-active: 16
        password: ''
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      ds_master_0_slave_1:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds_master_0_slave_1?serverTimezone=UTC&useSSL=false
        max-active: 16
        password: ''
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      ds_master_1:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds_master_1?serverTimezone=UTC&useSSL=false
        max-active: 16
        password: ''
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      ds_master_1_slave_0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds_master_1_slave_0?serverTimezone=UTC&useSSL=false
        max-active: 16
        password: ''
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      ds_master_1_slave_1:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds_master_1_slave_1?serverTimezone=UTC&useSSL=false
        max-active: 16
        password: ''
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      names: ds_master_0,ds_master_1,ds_master_0_slave_0,ds_master_0_slave_1,ds_master_1_slave_0,ds_master_1_slave_1


    sharding:
      binding-tables: t_order,t_order_item
      broadcast-tables: t_address
      default-data-source-name: ds_master_0
      default-database-strategy:
        inline:
          algorithm-expression: ds_$->{user_id % 2}
          sharding-column: user_id

      # 主从规则
      master-slave-rules:
        # inline 表达式使用的名称
        ds_0:
          master-data-source-name: ds_master_0
          slave-data-source-names: ds_master_0_slave_0, ds_master_0_slave_1
        ds_1:
          master-data-source-name: ds_master_1
          slave-data-source-names: ds_master_1_slave_0, ds_master_1_slave_1
      tables:
        t_order:
          actual-data-nodes: ds_$->{0..1}.t_order_$->{0..1}
          key-generator:
            column: order_id
            props:
              worker:
                id: 123
            type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: t_order_$->{order_id % 2}
              sharding-column: order_id
        t_order_item:
          actual-data-nodes: ds_$->{0..1}.t_order_item_$->{0..1}
          key-generator:
            column: order_item_id
            props:
              worker:
                id: 123
            type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: t_order_item_$->{order_id % 2}
              sharding-column: order_id
