spring:
  application:
    name: monitor
  cloud:
    nacos:
      server-addr: localhost:8848
  zipkin:
    base-url: http://localhost:9411
    # http://localhost:9411/
    discovery-client-enabled: false

server:
  port: 8828